---
title: "crime_weather_covid_WeatherExploration"
author: "Madlen Wilmes"
date: "5/19/2020"
output: html_document:
    df_print: paged
---

## TODO
# source the ReadData or read the csv
Pull in weather data (TODO: either script or pull fresh from BigQuery, currently separate script)

```{r read weather data}
daily_weather <- read.csv("crime_weather_day.csv")
daily_weather$date <- as.Date(daily_weather$date)
# transform into tsibble
daily_weather <- as_tsibble(daily_weather, index=date) %>% arrange(date)
```


```{r plot temperature over time}
daily_weather %>% 
  mutate(diff = date - lag(date)) %>%
  ggplot(aes(date, temperature)) + geom_line()
```


```{r plot snow depth over time}
daily_weather %>% 
  mutate(diff = date - lag(date)) %>%
  ggplot(aes(date, snow_depth)) + geom_point()
```


```{r Seasonal plot of precipitation}
daily_weather %>%
    index_by(year_month = ~ yearmonth(.)) %>% # monthly aggregates
  summarise(
    ttl_prec = sum(precipitation, na.rm = TRUE)
  ) %>%
  gg_subseries(ttl_prec) +
  ylab("Total Monthly Precipitation (in)") +
  xlab("Month/Year") +
  ggtitle("Seasonal subseries plot: Total monthly precipitation over the years")
ggsave("./img/SeasonalPlot_Precipitation.png", width = 7, height = 5)
```

The blue lines in each panel represents the mean per months (i.e., on average, May is the wettest month).

```{r Seasonal plot for temperature}
daily_weather %>%
    index_by(year_month = ~ yearmonth(.)) %>% # monthly aggregates
  summarise(
    avg_temp = mean(temperature, na.rm = TRUE)
  ) %>%
  gg_subseries(avg_temp) +
  ylab("Avg. Daily Temperature (F)") +
  xlab("Month/Year") +
  ggtitle("Seasonal subseries plot: Average monthly temperature over the years")
ggsave(",/img/SeasonalPlot_Temperature.png", width = 7, height = 5)
```
